### ISSUE TITLE
Blender EXML import

### ISSUE THREAD

**Issue by ScavangeR87** [emoose/MBINCompiler#65]
Got the following error while trying to import certain exml in Blender 2.77

Traceback (most recent call last):
  File "C:\Users\ScavangeR\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_import_exml.py", line 59, in execute
    vertexData = getFloatList(getProperty(xmlRoot, 'VertexStream'))
  File "C:\Users\ScavangeR\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_import_exml.py", line 32, in getFloatList
    list.append(float(p.get('value').replace(",", ".")))
ValueError: could not convert string to float: 'Non Numérique'

location: <unknown location>:-1

Tried replacing the value 'Non numérique' by 'n. def.' but no change.

**Comment by ScavangeR87** [comment]
Just bypassed this issue, manually changing "Non numérique" by "-1".

Don't know the logic behind this but hope it may help

**Comment by Atvaark** [comment]
You could help by writing which file had a "NaN"-value.

**Comment by ScavangeR87** [comment]
Sur, got it with MODELS\SPACE\SPACESTATION\MODULARPARTS\DOCK\BACK_SECTION.GEOMETRY.MBIN.PC (unpaked from NMSARC.973CACEA.pak)
1st occurence of faulty value @ line 343815

Got the same kind of errors with files giving me a '-infinit' value but can't remember wich one since i bapassed it straight away.

**Comment by Atvaark** [comment]
This looks like 2 separate issues.

1. float.ToString and double.ToString should be called with an IFormatProvider to stop NaN/infinite values from being localized.
Single.ToString(CultureInfo.InvariantCulture) should do the trick. Tools that read the .exml can then reliably check for NaN/infinite values. (XML serialization/deserialization should also be done with an invariant culture)
 
2. NaN half floats don't roundtrip 
[TkGeometryData.cs#L162](https://github.com/emoose/MBINCompiler/blob/07cdf5a3a708cbc55c42ae307435142716b65df2/MBINCompiler/Models/Structs/TkGeometryData.cs#L162) converts uint16 0xff00 to a "NaN" float.
On the other hand writing Single.NaN will write uint16 0xfe00.
I can't check if this has any impact on the game.
