### ISSUE TITLE
Latest MBINCompiler generating errors on a few ENTITY.MBIN files

### ISSUE THREAD

**Issue by RhesusTOR** [emoose/MBINCompiler#95]
Executing the latest release of MBINCompiler (or any of the 3 different version I have archived) on any of the following ENTITY.MBIN files generates the same type of error:
1. MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\LANDINGZONE\LANDINGZONE\ENTITIES\
   **LANDINGZONE.ENTITY.MBIN**
2. MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\TRADINGPOST\TRADINGPOST\ENTITIES\
   **OUTPOST.ENTITY.MBIN**
3. MODELS\SPACE\ANOMALY\ANOMALY\ENTITIES\
   **ANOMALY.ENTITY.MBIN**
4. MODELS\SPACE\ATLASSTATION\SHARED\ENTITIES\
   **ATLASSTATION.ENTITY.MBIN**
5. MODELS\SPACE\SPACESTATION\SPACESTATION\ENTITIES\
   **STATION.ENTITY.MBIN**

**The error thrown in every case:**

Unhandled Exception: System.Reflection.TargetInvocationException: 
Exception has been thrown by the target of an invocation. ---> 
System.Exception: Invalid list read, magic 00000000 expected xxxxxx01
   at MBINCompiler.Models.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at MBINCompiler.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   at MBINCompiler.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   at MBINCompiler.Models.NMSTemplate.DeserializeGenericList(BinaryReader reader, Int64 templateStartOffset, NMSTemplate parent)
   at MBINCompiler.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   at MBINCompiler.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   at MBINCompiler.MBINFile.GetData()
   at MBINCompiler.Program.DecompileFile(String input, String output)
   at MBINCompiler.Program.Main(String[] args)

**Comment by RhesusTOR** [comment]
Another one like the other 5:

MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\LANDINGPAD\LANDINGPADTRADER\ENTITIES\
**LANDINGPADTRADER.ENTITY.MBIN**
